Repository allanoguis/Hacktoberfest-2024, pull requests merged in 2024-10, with the labels that each got.

#15 Added new sprite
  images/gojirav2.png
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#16 Made ui changes in the game section
  gojirun/app/sections/game/page.js
  gojirun/app/sections/hero/page.js
  gojirun/package-lock.json
  gojirun/package.json
Labels: hacktoberfest, hacktoberfest-accepted

#24 Gojira game engine
  gojirun/app/components/Engine.tsx
  gojirun/app/sections/game/page.js
  gojirun/package-lock.json
  gojirun/package.json
Labels: hacktoberfest, hacktoberfest-accepted

#26 Collaborators section
  gojirun/app/globals.css
  gojirun/app/sections/collaborators/page.js
  gojirun/components.json
  gojirun/components/contributors-section.jsx
  gojirun/components/ui/button.jsx
  gojirun/components/ui/card.jsx
  gojirun/lib/utils.js
  gojirun/package-lock.json
  gojirun/tailwind.config.js
Labels: hacktoberfest, hacktoberfest-accepted

#32 Updated engine UI
  gojirun/components/engine.tsx
Labels: enhancement

#40 updated readme with the feedback line
  README.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#46 Update Game Engine
  gojirun/components/engine.tsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#54 47 collision bug in the game
  gojirun/app/images/gojirav3.svg
  gojirun/app/images/tank.svg
  gojirun/app/sections/game.jsx
  gojirun/components/engine.jsx
  gojirun/components/engine.tsx
  gojirun/components/gojira.js
  gojirun/package-lock.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#58 Basic Backend with SaveGame API is ready
  gojirun/.env
  gojirun/api/getAllGamesAPI/route.jsx
  gojirun/api/saveGameAPI/route.jsx
  gojirun/app/api/test.jsx
  gojirun/package-lock.json
  gojirun/package.json
  server/.gitignore
  server/controllers/gameController.js
  server/index.js
  server/package-lock.json
  server/package.json
  server/routes/route.js
  server/vercel.json
Labels: hacktoberfest, hacktoberfest-accepted

#61 56 background animation for the game
  gojirun/app/images/cloud-test.svg
  gojirun/app/images/cloud1.png
  gojirun/app/images/cloud2.png
  gojirun/app/images/cloud3.png
  gojirun/components/engine.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, design, game

#62 backend & Database for Saving the score of every game DONE
  gojirun/api/getAllGamesAPI/route.jsx
  gojirun/components/engine.jsx
  server/.gitignore
  server/controllers/gameController.js
  server/controllers/getGamesController.js
  server/firebaseConfig.js
  server/index.js
  server/package-lock.json
  server/package.json
  server/routes/route.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, back end

#63 made a page for all the game score, BUT HAVE not called getGames API
  gojirun/app/allgames/page.jsx
  server/firebaseConfig.js
Labels: hacktoberfest, hacktoberfest-accepted

#77 profile page added
  gojirun/app/ProfilePage/page.jsx
  gojirun/app/globals.css
  gojirun/app/sections/navigation.jsx
Labels: enhancement, help wanted, hacktoberfest, hacktoberfest-accepted
